//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karte()
        {
            this.Recenzije = new HashSet<Recenzije>();
            this.TransakcijaStavke = new HashSet<TransakcijaStavke>();
        }
    
        public int Id { get; set; }
        public string BrojKarte { get; set; }
        public System.DateTime datumPutovanja { get; set; }
        public string brojSjedista { get; set; }
        public bool Aktivna { get; set; }
        public int TipKarteId { get; set; }
        public int PosjecujeLokacijeId { get; set; }
    
        public virtual PosjecujeLokacije PosjecujeLokacije { get; set; }
        public virtual TipoviKarte TipoviKarte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzije> Recenzije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransakcijaStavke> TransakcijaStavke { get; set; }
    }
}
