//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnici()
        {
            this.AutorizacijskiToken = new HashSet<AutorizacijskiToken>();
            this.Kartice = new HashSet<Kartice>();
            this.Recenzije = new HashSet<Recenzije>();
            this.Transakcije = new HashSet<Transakcije>();
            this.SaobracajniDnevnik = new HashSet<SaobracajniDnevnik>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime datumRodjenja { get; set; }
        public string Spol { get; set; }
        public string Telefon { get; set; }
        public string ZemljaPorijekla { get; set; }
        public string Discriminator { get; set; }
        public string BrojIndeksa { get; set; }
        public byte[] slikaIndeksa { get; set; }
        public byte[] slikaPenzionerskeKartice { get; set; }
        public Nullable<int> GodineIskustva { get; set; }
        public string Email { get; set; }
        public bool isValid { get; set; }
        public string Zanimanje { get; set; }
        public int UlogeId { get; set; }
        public string Adresa { get; set; }
        public string Grad { get; set; }
        public string Hash { get; set; }
        public string Salt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizacijskiToken> AutorizacijskiToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kartice> Kartice { get; set; }
        public virtual Uloge Uloge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzije> Recenzije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcije> Transakcije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaobracajniDnevnik> SaobracajniDnevnik { get; set; }
    }
}
