//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Linije()
        {
            this.KretanjeAutobusa = new HashSet<KretanjeAutobusa>();
            this.PopustNaLiniji = new HashSet<PopustNaLiniji>();
            this.PosjecujeLokacije = new HashSet<PosjecujeLokacije>();
            this.Obavijesti = new HashSet<Obavijesti>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string TipLinije { get; set; }
        public string RedniBrojLinije { get; set; }
        public int PrevoznikId { get; set; }
        public int PolazakId { get; set; }
        public int DestinacijaId { get; set; }
        public string vrijemePolaska { get; set; }
        public Nullable<int> AutobusId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Autobusi Autobusi { get; set; }
        public virtual Gradovi Gradovi { get; set; }
        public virtual Gradovi Gradovi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KretanjeAutobusa> KretanjeAutobusa { get; set; }
        public virtual Prevoznici Prevoznici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopustNaLiniji> PopustNaLiniji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosjecujeLokacije> PosjecujeLokacije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavijesti> Obavijesti { get; set; }
    }
}
