//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popusti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Popusti()
        {
            this.PopustNaLiniji = new HashSet<PopustNaLiniji>();
            this.TransakcijaStavke = new HashSet<TransakcijaStavke>();
        }
    
        public int Id { get; set; }
        public string vrstaPopusta { get; set; }
        public float Postotak { get; set; }
        public System.DateTime DatumVazenjaPopusta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopustNaLiniji> PopustNaLiniji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransakcijaStavke> TransakcijaStavke { get; set; }
    }
}
