//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzije
    {
        public int Id { get; set; }
        public int Ocjena { get; set; }
        public string Opis { get; set; }
        public string Komentar { get; set; }
        public Nullable<int> KlijentiId { get; set; }
        public Nullable<int> KartaId { get; set; }
    
        public virtual Karte Karte { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
