//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaobracajniDnevnik
    {
        public int Id { get; set; }
        public System.DateTime vrijemeDolaska { get; set; }
        public string brojPutnogNaloga { get; set; }
        public int UposlenikId { get; set; }
        public int StanicaId { get; set; }
        public Nullable<bool> daLiJeKansnio { get; set; }
        public string vrijemeKasnjena { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Stanice Stanice { get; set; }
    }
}
