//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransakcijaStavke
    {
        public int Id { get; set; }
        public int Kolicina { get; set; }
        public float UkupnaCijena { get; set; }
        public int TransakcijaId { get; set; }
        public int KartaId { get; set; }
        public Nullable<int> PopustId { get; set; }
    
        public virtual Karte Karte { get; set; }
        public virtual Popusti Popusti { get; set; }
        public virtual Transakcije Transakcije { get; set; }
    }
}
