//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBusStation.API.Models
{
    using System;
    
    public partial class usp_mobile_Get_All_User_Transactions_Result1
    {
        public Nullable<System.DateTime> Column1 { get; set; }
        public string Status { get; set; }
        public float UkupnaCijena { get; set; }
        public System.DateTime datumPutovanja { get; set; }
        public float cijenaOdPolaska { get; set; }
        public Nullable<double> CijenaOdTrenutnogGradaDoDestinacije { get; set; }
        public string vrijemeDolaska { get; set; }
        public string Linija { get; set; }
        public string Grad { get; set; }
        public string vrijemePolaska { get; set; }
        public string VrijemeDolaskaNaZadnjuStanicu { get; set; }
    }
}
